apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-service.configmapName" . }}
  labels:
    app: {{ .Values.productName }}
    team: {{ .Values.team }}
data:
  config.txt: |
    {{ .Values.configData }}
