apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nginx-service.hpaName" . }}
  labels:
    app: {{ .Values.productName }}
    team: {{ .Values.team }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nginx-service.deploymentName" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds }}
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilizationWindowSeconds }}
      selectPolicy: Min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
