apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-service.serviceName" . }}
  labels:
    app: {{ .Values.productName }}
    team: {{ .Values.team }}
spec:
  selector:
    app: {{ .Values.productName }}
    team: {{ .Values.team }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
